name: Demo Workflow
on: [push]
jobs:
 Demo-Job:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v4
     - name: Some shell commands
       run: |
         echo "Hi we can enter multiple"
         echo "lines of shell commands"
         echo "here.."
     - name: List files in the repository
       run: |
         echo "Listing files in the repository(${{ github.workspace }}).."
         ls ${{ github.workspace }}
     - run: echo "Job's status is ${{ job.status }}"