name: Demo Workflow #2 (introducing change on test branch)
on: [push]
jobs:
 Demo-Job:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v4
     - name: Some shell commands
       run: |
         echo "Hi we can enter multiple"
         echo "lines of shell commands"
         echo "here.."
     - name: Print contents of README.md
       run: |
        cat README.md
     - name: List files in the repository
       run: |
         echo "Listing files in the repository(${{ github.workspace }}).."
         ls ${{ github.workspace }}
     - run: echo "Job's status is ${{ job.status }}"